version: '3.8'

services:
  centrifugo:
    image: centrifugo/centrifugo:v5
    command: centrifugo --config=config.json
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/centrifugo/config.json
    networks:
      - messaging_network

  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - CENTRIFUGO_URL=http://centrifugo:8000
  #     - CENTRIFUGO_API_KEY=api_key
  #     - PORT=8080
  #   depends_on:
  #     - centrifugo
  #   networks:
  #     - messaging_network

networks:
  messaging_network:
    driver: bridge
